# Generated by Django 5.0.9 on 2026-07-19 01:29

import apps.assets.models
import apps.tenancy.managers
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('projects', '0002_project_lead_user_and_more'),
        ('tenancy', '0004_rls_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Public code (docs/data-model.md: 'id (uuid, public code)').", unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_consumable', models.BooleanField(default=False, help_text='Defaulted from `category.default_is_consumable` at creation (docs/data-model.md §4); never both consumable and durable.')),
                ('serial_number', models.CharField(blank=True, default='', max_length=255)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In use'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('retired', 'Retired'), ('lost', 'Lost')], default='available', max_length=16)),
                ('condition', models.TextField(blank=True, default='')),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('qr_token', models.CharField(default=apps.assets.models._generate_qr_token, editable=False, max_length=64)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='PROTECT: a category in use by assets cannot be deleted out from under them.', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='catalog.category')),
                ('current_workload_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workload_assets', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='catalog.location')),
                ('project', models.ForeignKey(blank=True, help_text="NULL = general pool (docs/data-model.md §4). PROTECT: reassign an active project's assets before it can be deleted.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'assets_asset',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('doc', 'Document')], default='photo', max_length=10)),
                ('storage_key', models.CharField(help_text='Relative path/key on the storage backend (volume or, later, S3-compatible object storage) — never the binary itself.', max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=127)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.asset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets_attachment',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='TagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='assets.asset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='catalog.tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'assets_tag_link',
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(related_name='assets', through='assets.TagLink', to='catalog.tag'),
        ),
        migrations.CreateModel(
            name='AssetFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='assets.asset')),
                ('field_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_values', to='catalog.customfielddef')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'assets_asset_field_value',
                'indexes': [models.Index(fields=['tenant', 'asset'], name='assets_asse_tenant__0fcd75_idx')],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetfieldvalue',
            constraint=models.UniqueConstraint(fields=('asset', 'field_def'), name='uniq_asset_field_value_asset_field_def'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['tenant', 'asset'], name='assets_atta_tenant__0a2a93_idx'),
        ),
        migrations.AddIndex(
            model_name='taglink',
            index=models.Index(fields=['tenant', 'asset'], name='assets_tag__tenant__0e788d_idx'),
        ),
        migrations.AddIndex(
            model_name='taglink',
            index=models.Index(fields=['tenant', 'tag'], name='assets_tag__tenant__02767a_idx'),
        ),
        migrations.AddConstraint(
            model_name='taglink',
            constraint=models.UniqueConstraint(fields=('asset', 'tag'), name='uniq_tag_link_asset_tag'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'status'], name='assets_asse_tenant__155bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'category'], name='assets_asse_tenant__fe91e7_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'location'], name='assets_asse_tenant__33a64d_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'project'], name='assets_asse_tenant__135dd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('tenant', 'uuid'), name='uniq_asset_tenant_uuid'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('tenant', 'qr_token'), name='uniq_asset_tenant_qr_token'),
        ),
    ]
