# Generated by Django 5.0.9 on 2026-08-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rls_indexes_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Built-in link for this asset (product/procurement/docs page) so a category custom field is not needed for the near-universal case. Rendered as a clickable link by the UI — `apps.assets.serializers` restricts the scheme to http/https, since a stored `javascript:` URL would otherwise be a self-XSS vector on the detail screen.', max_length=500),
        ),
    ]
