# Generated by Django 5.0.9 on 2026-08-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase order'), ('receipt', 'Receipt'), ('quote', 'Quote'), ('warranty', 'Warranty'), ('manual', 'Manual / datasheet'), ('other', 'Other')], default='', help_text='Semantic label (invoice/PO/receipt/...) — see `DocType`. Blank for legacy rows and for files nobody bothered to classify; the expense prefill still offers those, just ranked below the tagged ones.', max_length=20),
        ),
    ]
