# Generated by Django 5.0.9 on 2026-07-20 01:27

import apps.tenancy.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_rls_indexes_search_vector'),
        ('projects', '0002_project_lead_user_and_more'),
        ('tenancy', '0004_rls_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('approval_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='The user who approved/rejected (docs/rbac.md §4). SET_NULL (actor-style reference), same pattern as ReorderRequest.approved_by.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(help_text='PROTECT: assets are never hard-deleted (docs/data-model.md §4); keeps the FK contract explicit.', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='assets.asset')),
                ('project', models.ForeignKey(blank=True, help_text='Optional project the reservation is charged to (general pool when NULL, docs/data-model.md §4).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('user', models.ForeignKey(help_text='The requester/holder. PROTECT: this is ownership, not an audit actor — a user holding reservations is soft-deactivated (is_active=False), never hard-deleted out from under their bookings.', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations_reservation',
                'ordering': ['-start_at'],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_condition', models.TextField(blank=True, default='')),
                ('checkin_condition', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='PROTECT: assets are never hard-deleted (docs/data-model.md §4).', on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='assets.asset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('user', models.ForeignKey(help_text='The holder. PROTECT — ownership, not an audit actor (see Reservation.user).', on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, help_text='Optional originating reservation (a walk-up checkout has none). SET_NULL keeps the possession record if the reservation row is later removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='reservations.reservation')),
            ],
            options={
                'db_table': 'reservations_checkout',
                'ordering': ['-checked_out_at'],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'asset', 'start_at'], name='reservation_tenant__3d79f4_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'start_at', 'end_at'], name='reservation_tenant__89dab3_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'status'], name='reservation_tenant__095897_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('end_at__gt', models.F('start_at'))), name='reservation_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['tenant', 'asset'], name='reservation_tenant__e3f1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['tenant', 'user'], name='reservation_tenant__b08427_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.CheckConstraint(check=models.Q(('due_at__gt', models.F('checked_out_at'))), name='checkout_due_after_checkout'),
        ),
    ]
