"""Bug fix (F4 gap): add the terminal `Reservation.Status.COMPLETED` choice.

State-only (`AlterField` on `status`'s `choices`, generated by
`makemigrations`) -- no SQL beyond Django's own column comment/choices
bookkeeping. `COMPLETED` is deliberately NOT in `Reservation.ACTIVE_STATUSES`
(`apps/reservations/models.py`), so it needs no change to the `0002` GiST
exclusion constraint's WHERE clause (`'pending', 'approved', 'fulfilled'`) --
a `completed` row already falls outside both the app-level conflict
pre-check and the DB constraint without any constraint SQL edit.

`checkout.perform_checkin` (`apps/reservations/checkout.py`) now moves a
reservation-backed checkout's `Reservation` from `fulfilled` to this new
`completed` status when the asset is actually checked back in, fixing the
bug where a `fulfilled` reservation's window blocked re-booking forever.
"""
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_rls_indexes_exclusion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("fulfilled", "Fulfilled"),
                    ("expired", "Expired"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
