# Generated by Django 5.0.9 on 2026-07-19 17:56

import apps.tenancy.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_rls_indexes_search_vector'),
        ('catalog', '0002_rls_policies'),
        ('tenancy', '0004_rls_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(max_length=32)),
                ('quantity_on_hand', models.IntegerField(default=0, help_text='Derived/reconciled against the StockTxn ledger sum (docs/data-model.md §2) — never set directly by client writes.')),
                ('reorder_threshold', models.IntegerField(default=0)),
                ('reorder_target', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(help_text='PROTECT: a consumable asset with stock history cannot be deleted out from under it (assets are never hard-deleted anyway, docs/data-model.md §4, but this keeps the FK contract explicit).', on_delete=django.db.models.deletion.PROTECT, related_name='stock_item', to='assets.asset')),
                ('bin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='catalog.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'stock_stock_item',
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReorderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_requests_made', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_requests', to='stock.stockitem')),
            ],
            options={
                'db_table': 'stock_reorder_request',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='StockTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Signed quantity change (positive=in, negative=out).')),
                ('reason', models.CharField(choices=[('receive', 'Receive'), ('consume', 'Consume'), ('adjust', 'Adjust'), ('correction', 'Correction')], max_length=16)),
                ('ref', models.CharField(blank=True, default='', help_text='Free reference.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_txns', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_txns', to='stock.stockitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'stock_stock_txn',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['tenant'], name='stock_stock_tenant__e5e576_idx'),
        ),
        migrations.AddIndex(
            model_name='reorderrequest',
            index=models.Index(fields=['tenant', 'stock_item', 'status'], name='stock_reord_tenant__dd0cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktxn',
            index=models.Index(fields=['tenant', 'stock_item', 'created_at'], name='stock_stock_tenant__4ec2d2_idx'),
        ),
    ]
