# Generated by Django 5.0.9 on 2026-07-20 10:31

import apps.tenancy.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0004_rls_policies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recipient",
                    models.EmailField(
                        help_text="The actual address used for this send.", max_length=254
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Domain event key, e.g. 'low_stock_crossed', 'reservation_confirmed'.",
                        max_length=100,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Provider class name used for this send, e.g. 'ConsoleProvider'.",
                        max_length=32,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The account this email was sent to, if any (see module docstring).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_email_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "event_type", "created_at"],
                        name="notificatio_tenant__273569_idx",
                    )
                ],
            },
            managers=[
                ("objects", apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPref",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("email_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification_pref",
                "indexes": [
                    models.Index(fields=["tenant", "user"], name="notificatio_tenant__dde4c9_idx")
                ],
            },
            managers=[
                ("objects", apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="notificationpref",
            constraint=models.UniqueConstraint(
                fields=("user", "event_type"), name="notif_pref_unique_user_event"
            ),
        ),
    ]
