# Generated by Django 5.0.9 on 2026-07-25 00:31
"""Add the per-tenant ``EmailSettings`` config table + its RLS backstop.

``EmailSettings`` is a new ``TenantScopedModel`` (per-tenant email-provider
configuration), so it needs the exact same RLS tenant-isolation policy as every
other tenant-owned table (the R4 backstop). RLS is added here via the shared
``apps.tenancy.db.enable_rls_sql``/``disable_rls_sql`` helpers so the policy
predicate is byte-identical to every other tenant table — the app-level
``TenantScopedManager`` filter and the DB policy cannot drift. Fail-closed:
no ``app.current_tenant`` GUC -> ``tenant_id = NULL`` -> zero rows.

No extra indexes are owed: exactly one row per tenant (the
``notifications_email_settings_one_per_tenant`` unique constraint on
``tenant``) and the ``tenant`` FK's own ``db_index`` cover the only access
path (tenant + pk lookup). No exclusion constraint / trigger / search vector —
this is a plain config row, not a domain entity.
"""
from __future__ import annotations

import apps.tenancy.managers
import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.db import disable_rls_sql, enable_rls_sql


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rls_policies'),
        ('tenancy', '0004_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('console', 'Console (dev/test — logs only)'), ('brevo', 'Brevo')], default='console', max_length=20)),
                ('sender_email', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.CharField(blank=True, max_length=255)),
                ('api_key_encrypted', models.BinaryField(blank=True, default=b'')),
                ('api_key_last4', models.CharField(blank=True, max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notifications_email_settings',
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='emailsettings',
            constraint=models.UniqueConstraint(fields=('tenant',), name='notifications_email_settings_one_per_tenant'),
        ),
        # RLS backstop (R4) — enable RLS + tenant-isolation policy, identical
        # predicate to every other tenant table. Reverse drops the policy and
        # disables RLS.
        migrations.RunSQL(
            sql=enable_rls_sql('notifications_email_settings'),
            reverse_sql=disable_rls_sql('notifications_email_settings'),
        ),
    ]
