# Generated by Django 5.0.9 on 2026-07-30 18:35
#
# Code-review follow-up: lowers the `SessionSettings.absolute_timeout_hours`
# ceiling from `MaxValueValidator(720)` (30 days) to `MaxValueValidator(168)`
# (7 days) -- see `apps.tenancy.models.SessionSettings` and
# `config/settings/base.py`'s `SESSION_COOKIE_AGE` (reverted 30d -> 7d in the
# same change) for why. Purely an `AlterField` on the field's Python-level
# validators; no schema/column/constraint change and no RLS impact, so this is
# reversible with Django's default auto-generated reverse (re-applying the
# previous `MaxValueValidator(720)`), and doesn't need `db-migration-specialist`
# review beyond this note.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_sessionsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsettings',
            name='absolute_timeout_hours',
            field=models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
    ]
