# Generated by Django 5.0.9 on 2026-07-19 00:39

import apps.tenancy.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_is_consumable', models.BooleanField(default=False, help_text='Default for Asset.is_consumable when an asset is created under this category (docs/data-model.md §4).')),
                ('requires_approval', models.BooleanField(default=False, help_text='Drives the per-category reservation/checkout approval config (docs/rbac.md §4).')),
                ('requires_calibration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='PROTECT: a parent category with children cannot be deleted until its children are re-parented/removed first (avoids silently orphaning or cascade-wiping a whole subtree).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'catalog_category',
                'ordering': ['tenant_id', 'name'],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Machine key, e.g. 'vram_gb'.", max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('date', 'Date'), ('enum', 'Enum'), ('json', 'JSON')], max_length=8)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('enum_options', models.JSONField(blank=True, default=list, help_text="List of allowed values when data_type='enum'; ignored otherwise.")),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_defs', to='catalog.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'catalog_custom_field_def',
                'ordering': ['category_id', 'order', 'id'],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'catalog_location',
                'ordering': ['tenant_id', 'name'],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'catalog_tag',
                'ordering': ['name'],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'parent'], name='catalog_cat_tenant__e30d07_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'parent', 'name'), name='uniq_category_tenant_parent_name'),
        ),
        migrations.AddIndex(
            model_name='customfielddef',
            index=models.Index(fields=['tenant', 'category'], name='catalog_cus_tenant__5cc117_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfielddef',
            constraint=models.UniqueConstraint(fields=('tenant', 'category', 'key'), name='uniq_field_def_tenant_category_key'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'parent'], name='catalog_loc_tenant__c5be89_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('tenant', 'parent', 'name'), name='uniq_location_tenant_parent_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_tag_tenant_name'),
        ),
    ]
