# Generated by Django 5.0.9 on 2026-07-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rls_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddef',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('date', 'Date'), ('enum', 'Enum'), ('json', 'JSON'), ('url', 'URL')], max_length=8),
        ),
    ]
