# Generated by Django 5.0.9 on 2026-08-05 07:08

import apps.tenancy.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_seed_project_grant_permissions'),
        ('tenancy', '0007_tenant_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_customized',
            field=models.BooleanField(default=False, help_text="True once an admin has edited this role's permission set away from the `SYSTEM_ROLE_PERMISSIONS` defaults. Load-bearing: `apps.rbac.seed.seed_roles_for_tenant` is idempotent and `get_or_create`s every default grant, so without this flag a re-run (migration backfill, management command) would silently re-add grants an admin deliberately removed. 'Reset to defaults' clears it."),
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('grant', 'Always allow'), ('deny', 'Never allow')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='rbac.permission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_user_permission_override',
                'ordering': ['user_id', 'permission_id'],
                'indexes': [models.Index(fields=['tenant', 'user'], name='rbac_user_p_tenant__fac539_idx')],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='userpermissionoverride',
            constraint=models.UniqueConstraint(fields=('user', 'permission'), name='uniq_user_permission_override'),
        ),
    ]
