# Generated by Django 5.0.9 on 2026-07-25 23:16
#
# Adds the forgot-password reset-token table. Like every other tenant-owned
# table it ships the byte-identical fail-closed tenant-isolation RLS policy via
# `apps.tenancy.db.enable_rls_sql` (R4 backstop — the app-level
# `TenantScopedManager` filter and the DB policy cannot drift). Reversible +
# idempotent-safe (`DROP POLICY IF EXISTS`).

import apps.tenancy.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.tenancy.db import disable_rls_sql, enable_rls_sql


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenancy', '0004_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_password_reset_token',
                'indexes': [models.Index(fields=['tenant', 'user'], name='accounts_pa_tenant__6fc74b_idx')],
            },
            managers=[
                ('objects', apps.tenancy.managers.TenantScopedManager()),
            ],
        ),
        migrations.RunSQL(
            sql=enable_rls_sql('accounts_password_reset_token'),
            reverse_sql=disable_rls_sql('accounts_password_reset_token'),
        ),
    ]
